dnn apply to batch
Hattomo/kaikai_AI pull request #179
Opened 2020-11-26 13:59 UTC by kaikai529

## Description

dnn apply to batch training.
## Related Issues and Reference

## Test

2020-11-27 01:16 UTC, Hattomo requested changes
NNは全体的に性能下がってる気がする
orをandにすると、学習進まない
CNN はまだみてないけど

2020-11-27 01:16 UTC, Hattomo commented on dnn/main.py
> -npfiles.save(orNN)
Do not delete this

2020-11-27 01:16 UTC, Hattomo commented on tests/test_dnn_main.py
> -    npfiles.save(orNN)
Do not delete this

2020-11-27 01:16 UTC, Hattomo commented on tests/test_dnn_main.py
> -
Do not delete this

2020-11-27 01:16 UTC, Hattomo commented on tests/test_dnn_main.py
> -
same

2020-11-27 01:16 UTC, Hattomo commented on tests/test_dnn_main.py
> -    # test chart
same

2020-11-27 03:22 UTC, kaikai529 commented on dnn/main.py
> -npfiles.save(orNN)
ok

2020-11-27 03:22 UTC, kaikai529 commented on tests/test_dnn_main.py
> -    npfiles.save(orNN)
why?

2020-11-27 03:22 UTC, kaikai529 commented on tests/test_dnn_main.py
> -
why?

2020-11-27 03:22 UTC, kaikai529 commented on tests/test_dnn_main.py
> -
why?

2020-11-27 03:23 UTC, kaikai529 commented on tests/test_dnn_main.py
> -    # test chart
why?

2020-11-28 03:20 UTC, kaikai529 commented
orはw_method=Xavier、 actfunc=sigmoidでうまくいきやすいです。
andはw_method=he、 actfunc=tanhでうまくいきやすいです。
学習データ、重みの初期値、活性化関数によって学習のしやすさは違うので
理論が正しければマージしてください。

2020-11-30 10:35 UTC, kaikai529 commented
add batch training to dnn,cnn
refactor dnn 
change xivier to xavier
change dataset structure
delete some files
rename some files
make convolution_neural_network
format

we can't use mnist data!
please check this refactor codes

2020-12-04 15:03 UTC, Hattomo reviewed
My memo😫

2020-12-04 15:03 UTC, Hattomo commented on cnn/convolution_layer.py
> +        train_ratio = 0.01
why

2020-12-04 15:03 UTC, Hattomo commented on cnn/convolution_neural_network.py
> +class Convolution_Neural_Network():
why this name?

2020-12-04 15:03 UTC, Hattomo commented on cnn/convolution_neural_network.py
> +        for i in range(len(self.structure) - 1, 0):
why

2020-12-04 15:03 UTC, Hattomo commented on cnn/fully_connenct_layer.py
> +        up_error = super().backpropagation(train_data, train_label)
isexternal?

2020-12-04 15:03 UTC, Hattomo commented on dataset/dataset.py
> +    #     original_data = np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
comment?

2020-12-04 15:03 UTC, Hattomo commented on dataset/dataset.py
> +    return data, label
Donot test here?

2020-12-04 15:03 UTC, Hattomo commented on dnn/neural_network.py
> -    def forwardpropagation(self, train_data, istrain=True):
isTrain?

2020-12-04 15:03 UTC, Hattomo commented on dnn/neural_network.py
> -    def backpropagation(self, train_data, train_label, isexternal=False):
isexternal?

2020-12-04 15:03 UTC, Hattomo commented on tests/test_dataset.py
> +#     assert (np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) == label).all()
comment out?

2020-12-04 15:03 UTC, Hattomo commented on dnn/neural_network.py
> +            tmp = self.diffact(self.z[-i - 2][:, 1:]) * (tmp @ self.weight[-i - 1][:, 1:] @ self.do[-i - 1][:-1, :-1].T)
?

2020-12-04 15:03 UTC, Hattomo commented on dataset/dataset.py
> +    #     original_data = np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
train&test?

2020-12-05 01:06 UTC, kaikai529 commented on cnn/convolution_layer.py
> +        train_ratio = 0.01
Need to initiate train_ratio.

2020-12-05 01:45 UTC, kaikai529 reviewed
確認してください

2020-12-05 01:45 UTC, kaikai529 commented on cnn/convolution_neural_network.py
> +class Convolution_Neural_Network():
Cnnだから。
求めてる答えがわからない

2020-12-05 01:45 UTC, kaikai529 commented on cnn/convolution_neural_network.py
> +        for i in range(len(self.structure) - 1, 0):
Whyとは何について言ってる？

2020-12-05 01:45 UTC, kaikai529 commented on cnn/fully_connenct_layer.py
> +        up_error = super().backpropagation(train_data, train_label)
Is externalなしで全部returnするようにした

2020-12-05 01:45 UTC, kaikai529 commented on dataset/dataset.py
> +    #     original_data = np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
コメントアウトしてるのは単純にミス！変更を少し加えないといけない
Trainとtestをわかてるのはデータの構造が違いから
Train の構造は(detasetsize//batchsize,batchsize,data)
Testの構造は(testsize,data)みたいにしたかったから

2020-12-05 01:45 UTC, kaikai529 commented on dataset/dataset.py
> +    return data, label
求められている答えがわかんない
Trainとtestをわけてるのは誤差を別々にするためでもある

2020-12-05 01:45 UTC, kaikai529 commented on dnn/neural_network.py
> -    def forwardpropagation(self, train_data, istrain=True):
Dnnのtest()でdropoutをゼロにしてistrainを引数から消した
だから、testを一回確認してみて

2020-12-05 01:45 UTC, kaikai529 commented on dnn/neural_network.py
> -    def backpropagation(self, train_data, train_label, isexternal=False):
全部tmpをreturnするようにした

2020-12-05 01:45 UTC, kaikai529 commented on dnn/neural_network.py
> +            tmp = self.diffact(self.z[-i - 2][:, 1:]) * (tmp @ self.weight[-i - 1][:, 1:] @ self.do[-i - 1][:-1, :-1].T)
重みが式と反対だから形を変えたんだと思う
ともちゃんも確認してみて
https://imagingsolution.net/deep-learning/backpropagation/

2020-12-05 01:45 UTC, kaikai529 commented on tests/test_dataset.py
> +#     assert (np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) == label).all()
データの構造が違うからmergeされたら書き換えます

2020-12-06 06:23 UTC, kaikai529 commented on cnn/convolution_neural_network.py
> +class Convolution_Neural_Network():
convolutional_neural_network

2020-12-06 06:23 UTC, kaikai529 commented on dnn/neural_network.py
> -    def forwardpropagation(self, train_data, istrain=True):
・dropoutを引数で持ってくる

2020-12-06 06:23 UTC, kaikai529 commented on dnn/neural_network.py
> +            self.__dropout_shake()
batchごと？epochごと？

2020-12-06 07:31 UTC, Hattomo approved these changes

2020-12-06 07:31 UTC, merged