refactor nn
Hattomo/kaikai_AI pull request #89
Opened 2020-11-09 15:02 UTC by kaikai529

## Description

スマートにしました
## Related Issues and Reference

## Test

2020-11-09 16:43 UTC, Hattomo requested changes

2020-11-09 16:43 UTC, Hattomo commented on dnn/neural_network.py
>              diffact = af.diffsigmoid
```suggestion

```

2020-11-09 16:43 UTC, Hattomo commented on dnn/neural_network.py
> +            tmp = self.diffact(self.z[-i - 2][1:]) * (self.weight[-i - 1][:, 1:].T @ tmp)
コメント足したほうがいいかも。
何やってるかさらに分かりにくくなってく

2020-11-10 05:12 UTC, kaikai529 commented on dnn/neural_network.py
> +            tmp = self.diffact(self.z[-i - 2][1:]) * (self.weight[-i - 1][:, 1:].T @ tmp)
じゃあ、ここだけコメント付けます。

2020-11-10 05:56 UTC, Hattomo approved these changes
LGTM

2020-11-10 05:56 UTC, Hattomo approved these changes
LGTM

2020-11-10 05:57 UTC, merged